
GOPATH:=$(shell go env GOPATH)
.PHONY: init
init:
	go get -u google.golang.org/protobuf/proto@latest
	go get -u google.golang.org/protobuf/cmd/protoc-gen-go@latest
	go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
	go get github.com/micro/micro/v3/cmd/protoc-gen-micro@latest
	go get github.com/google/gnostic/cmd/protoc-gen-openapi@latest
.PHONY: proto
proto:
	protoc --openapi_out=. --proto_path=. --micro_out=. --go_out=. --go-grpc_out=. proto/exchange_rate.proto

docs:
	protoc --openapi_out=. --proto_path=. --micro_out=. --go_out=. proto/exchange_rate.proto
	@redoc-cli bundle api-exchange_rate.json

.PHONY: build
build:
	go build -o exchange_rate *.go

.PHONY: test
test:
	go test -v ./... -cover

.PHONY: docker
docker:
	docker build . -t exchange_rate:latest
